src/java/main/de/iteratec/iteraplan/businesslogic/reports/query/options/GraphicalReporting/Cluster/ClusterOptionsBean.java
/*
 * This file is part of "Smart360 EA".
 *
 * Smart360 EA is a lean IT Management web application developed by Smart360.
 * Smart360 EA is based on and powered by iteraplan (an IT Governance web application) developed by iteratec GmbH.
 * Copyright (C) 2004-2014 iteratec GmbH
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by
 * the Free Software Foundation with the addition of the following permission
 * added to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED
 * WORK IN WHICH THE COPYRIGHT IS OWNED BY ITERATEC, ITERATEC DISCLAIMS THE
 * WARRANTY OF NON INFRINGEMENT OF THIRD PARTY RIGHTS. FOR ANY PART OF THE COVERED
 * WORK IN WHICH THE COPYRIGHT IS OWNED BY Smart360, Smart360 DISCLAIMS THE
 * WARRANTY OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License
 * version 3, these Appropriate Legal Notices must retain the display of the
 * "iteraplan" logo. If the display of the logo is not reasonably
 * feasible for technical reasons, the Appropriate Legal Notices must display
 * the words "Powered by iteraplan".
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see http://www.gnu.org/licenses or write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301 USA.
 * 
 * You can contact iteratec GmbH headquarters at Inselkammerstr. 4
 * 82008 Munich - Unterhaching, Germany, or at email address info@iteratec.de.
 */
package de.iteratec.iteraplan.businesslogic.reports.query.options.GraphicalReporting.Cluster;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import com.google.common.collect.ImmutableList;

import de.iteratec.iteraplan.businesslogic.reports.query.options.ManageReportBeanBase;
import de.iteratec.iteraplan.businesslogic.reports.query.options.GraphicalReporting.GraphicalExportOptionsWithOrderedList;
import de.iteratec.iteraplan.businesslogic.reports.query.options.TabularReporting.ExportOption;
import de.iteratec.iteraplan.common.Constants;
import de.iteratec.iteraplan.common.error.IteraplanBusinessException;
import de.iteratec.iteraplan.common.util.CollectionUtils;
import de.iteratec.iteraplan.model.TypeOfBuildingBlock;
import de.iteratec.iteraplan.model.attribute.AttributeType;
import de.iteratec.iteraplan.model.attribute.BBAttribute;
import de.iteratec.iteraplan.presentation.SpringGuiFactory;


/**
 * Container for the parameters of the Cluster diagram.
 */
public class ClusterOptionsBean extends GraphicalExportOptionsWithOrderedList implements IClusterOptions, Serializable {

  /** Serialization version. */
  private static final long                   serialVersionUID               = 4677329221498139781L;
  private int                                 selectedAttributeType          = -1;
  private List<String>                        selectedAttributeValues        = CollectionUtils.arrayList();

  private List<AttributeType>                 availableAttributeTypes        = CollectionUtils.arrayList();

  private int                                 selectedHierarchicalUpperLevel = 1;
  private int                                 selectedHierarchicalLowerLevel = 1;

  private String                              selectedHierarchicalLevels;

  private static final String                 RANGE_SPLIT                    = "_";

  private int                                 availableHierarchicalLevels;

  private String                              selectedClusterMode            = Constants.REPORTS_EXPORT_CLUSTER_MODE_BB;

  private final List<String>                  availableClusterModes          = CollectionUtils.arrayList();

  private boolean                             swimlaneContent;

  private static final int                    NONE                           = -1;

  private Map<String, ClusterSecondOrderBean> secondOrderBeansMap            = new HashMap<String, ClusterSecondOrderBean>();

  private boolean                             checkAllBox                    = true;
  /**
   * Contains the building block types in the order in which they are to be drawn.
   */
  private List<String>                        typeOrder;

  public ClusterOptionsBean() {
    super();
    this.setSelectedBbType(Constants.BB_BUSINESSDOMAIN_PLURAL);
    initializeClusterOptions();
  }

  private void initializeClusterOptions() {

    getColorOptionsBean().setAvailableColors(SpringGuiFactory.getInstance().getClusterColors());

    availableClusterModes.add(Constants.REPORTS_EXPORT_CLUSTER_MODE_BB);
    availableClusterModes.add(Constants.REPORTS_EXPORT_CLUSTER_MODE_ATTRIBUTE);

    setSelectedGraphicFormat(Constants.REPORTS_EXPORT_GRAPHICAL_SVG);
    setAvailableGraphicFormats(ExportOption.getGraphicalExportOptions(false));

    typeOrder = new ArrayList<String>();
  }

  /**
   * Initializes the second order beans of a cluster graphic.
   * 
   * @param typeToAttributeListMap
   *          A map that links every connected {@link de.iteratec.iteraplan.model.BuildingBlockType BuildingBlockType}
   *          to a list of {@link AttributeType} containing its attributes.
   * @param connectedAttributes
   *          A list of the connected {@link BBAttribute}s. The list is empty if an attribute type
   *          is selected for the main axis. The list is filled with the related attributes for
   *          which the user has permissions if a building block type is selected for the main axis.
   */
  public void configureSecondOrderBeans(Map<TypeOfBuildingBlock, List<BBAttribute>> typeToAttributeListMap, List<BBAttribute> connectedAttributes) {

    // Add the building block types
    for (Entry<TypeOfBuildingBlock, List<BBAttribute>> entry : typeToAttributeListMap.entrySet()) {
      final String representedType = entry.getKey().getValue();

      final TypeOfBuildingBlock tobb = TypeOfBuildingBlock.getTypeOfBuildingBlockByString(getSelectedBbType());
      if (tobb.equals(entry.getKey()) && Constants.REPORTS_EXPORT_CLUSTER_MODE_BB.equals(selectedClusterMode)) {
        final List<String> selfReferences = entry.getKey().getSelfReferencesPropertyKeys();
        for (String secondOrderBeanName : selfReferences) {
          if (!secondOrderBeanName.endsWith(".parent") && !secondOrderBeanName.endsWith(".generalisation")) {
            addSecondOrderBean(secondOrderBeanName, representedType, entry.getValue(), ClusterSecondOrderBean.BUILDING_BLOCK_BEAN,
                Integer.valueOf(-1));
          }
        }
      }
      else {
        addSecondOrderBean(representedType, representedType, entry.getValue(), ClusterSecondOrderBean.BUILDING_BLOCK_BEAN, Integer.valueOf(-1));
      }
    }

    // Add the attributes
    for (BBAttribute attribute : connectedAttributes) {
      addSecondOrderBean(attribute.getName(), attribute.getName(), new ArrayList<BBAttribute>(), ClusterSecondOrderBean.ATTRIBUTE_BEAN,
          attribute.getId());
    }

  }

  /**
   * Reorders building blocks according to user's input.
   */
  @Override
  public void refreshOrder() {
    if (getMovedItem() != NONE) {
      switch (getMoveType()) {
        case TOP:
          typeOrder.add(0, typeOrder.remove(getMovedItem()));
          break;
        case UP:
          if (getMovedItem() > 0) {
            typeOrder.add(getMovedItem() - 1, typeOrder.remove(getMovedItem()));
          }
          break;
        case DOWN:
          if (getMovedItem() < (typeOrder.size() - 1)) {
            typeOrder.add(getMovedItem() + 1, typeOrder.remove(getMovedItem()));
          }
          break;
        case BOTTOM:
          final int position = typeOrder.size() - 1;
          typeOrder.add(position, typeOrder.remove(getMovedItem()));
          break;
        default:
          // Nothing to do.
          break;
      }
      // reset after performing movement
      setMovedItem(NONE);
      setMove(Movement.HOLD_POSITION.toInteger());
    }

    moveUncheckedElementsToBottom();
  }

  private void moveUncheckedElementsToBottom() {
    final LinkedList<String> toBottom = new LinkedList<String>();
    for (String type : typeOrder) {
      final ClusterSecondOrderBean secondOrderBean = getSecondOrderBean(type);
      if (secondOrderBean == null) {
        throw new IteraplanBusinessException();
      }
      if (!secondOrderBean.isSelected()) {
        toBottom.addLast(type);
      }
    }
    for (String type : toBottom) {
      typeOrder.remove(type);
      typeOrder.add(typeOrder.size(), type);
    }
  }

  public List<ClusterSecondOrderBean> getSecondOrderBeans() {
    final ArrayList<ClusterSecondOrderBean> colorDimensions = new ArrayList<ClusterSecondOrderBean>(secondOrderBeansMap.size());
    for (String type : typeOrder) {
      final ClusterSecondOrderBean secondOrderBean = getSecondOrderBean(type);
      if (secondOrderBean != null) {
        colorDimensions.add(secondOrderBean);
      }
    }
    return colorDimensions;
  }

  @Override
  public void switchDimensionOptionsToPresentationMode() {

    super.switchDimensionOptionsToPresentationMode();
    for (ClusterSecondOrderBean bean : secondOrderBeansMap.values()) {
      bean.getColorOptions().switchToPresentationMode();
    }
  }

  @Override

src/java/main/de/iteratec/iteraplan/businesslogic/reports/query/options/GraphicalReporting/Landscape/ManageLandscapeDiagramMemoryBean.java
/*
 * This file is part of "Smart360 EA".
 *
 * Smart360 EA is a lean IT Management web application developed by Smart360.
 * Smart360 EA is based on and powered by iteraplan (an IT Governance web application) developed by iteratec GmbH.
 * Copyright (C) 2004-2014 iteratec GmbH
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by
 * the Free Software Foundation with the addition of the following permission
 * added to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED
 * WORK IN WHICH THE COPYRIGHT IS OWNED BY ITERATEC, ITERATEC DISCLAIMS THE
 * WARRANTY OF NON INFRINGEMENT OF THIRD PARTY RIGHTS. FOR ANY PART OF THE COVERED
 * WORK IN WHICH THE COPYRIGHT IS OWNED BY Smart360, Smart360 DISCLAIMS THE
 * WARRANTY OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License
 * version 3, these Appropriate Legal Notices must retain the display of the
 * "iteraplan" logo. If the display of the logo is not reasonably
 * feasible for technical reasons, the Appropriate Legal Notices must display
 * the words "Powered by iteraplan".
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see http://www.gnu.org/licenses or write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301 USA.
 * 
 * You can contact iteratec GmbH headquarters at Inselkammerstr. 4
 * 82008 Munich - Unterhaching, Germany, or at email address info@iteratec.de.
 */
package de.iteratec.iteraplan.businesslogic.reports.query.options.GraphicalReporting.Landscape;

import java.util.Map;

import de.iteratec.iteraplan.businesslogic.reports.query.options.QueryResult;
import de.iteratec.iteraplan.businesslogic.reports.query.options.ReportMemBean;
import de.iteratec.iteraplan.businesslogic.reports.query.options.GraphicalReporting.GraphicalExportBaseOptions;
import de.iteratec.iteraplan.common.util.CollectionUtils;


public class ManageLandscapeDiagramMemoryBean extends ReportMemBean {

  private static final long              serialVersionUID = -3280461167656430182L;

  private boolean                        reportUpdated;

  /**
   * Map holding the {@link QueryResult}s of the report
   */
  private final Map<String, QueryResult> queryResults     = CollectionUtils.hashMap();

  /**
   * Holds the query name for the currently active query.
   * Possible values can be queried from the {@link GraphicalExportBaseOptions#getQueryResultNames() OptionsBean}.
   */
  private String                         queryResultName;

  private LandscapeOptionsBean           landscapeOptions = new LandscapeOptionsBean();

  public boolean isReportUpdated() {
    return reportUpdated;
  }

  public void setReportUpdated(boolean reportUpdated) {
    this.reportUpdated = reportUpdated;
  }

  public void setGraphicalOptions(LandscapeOptionsBean landscapeOptions) {
    this.landscapeOptions = landscapeOptions;
  }

  public LandscapeOptionsBean getGraphicalOptions() {
    return landscapeOptions;
  }

  public String getQueryResultName() {
    return queryResultName;
  }

  public void setQueryResultName(String queryResultName) {
    this.queryResultName = queryResultName;
  }

  /**
   * @return the {@link QueryResult} for the currently set {@link #queryResultName}
   */
  public QueryResult getQueryResult() {
    return getQueryResult(getQueryResultName());
  }

  /**
   * @param queryName
   *          String-Key to access a certain {@link QueryResult}, see {@link #queryResultName}
   * @return the {@link QueryResult} for the given queryName
   */
  public QueryResult getQueryResult(String queryName) {
    return queryResults.get(queryName);
  }

  /**
   * Adds the given {@link QueryResult} object to the memory bean, replacing any already existing
   * {@link QueryResult} with the same name.
   * @param queryResult
   *          The {@link QueryResult} to set. Can't be null.
   */
  public void setQueryResult(QueryResult queryResult) {
    queryResults.put(queryResult.getQueryName(), queryResult);
  }

  public Map<String, QueryResult> getQueryResults() {
    return this.queryResults;
  }

}

src/java/main/de/iteratec/iteraplan/businesslogic/reports/query/options/GraphicalReporting/Line/ILineOptionsBean.java
/*
 * This file is part of "Smart360 EA".
 *
 * Smart360 EA is a lean IT Management web application developed by Smart360.
 * Smart360 EA is based on and powered by iteraplan (an IT Governance web application) developed by iteratec GmbH.
 * Copyright (C) 2004-2014 iteratec GmbH
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by
 * the Free Software Foundation with the addition of the following permission
 * added to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED
 * WORK IN WHICH THE COPYRIGHT IS OWNED BY ITERATEC, ITERATEC DISCLAIMS THE
 * WARRANTY OF NON INFRINGEMENT OF THIRD PARTY RIGHTS. FOR ANY PART OF THE COVERED
 * WORK IN WHICH THE COPYRIGHT IS OWNED BY Smart360, Smart360 DISCLAIMS THE
 * WARRANTY OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License
 * version 3, these Appropriate Legal Notices must retain the display of the
 * "iteraplan" logo. If the display of the logo is not reasonably
 * feasible for technical reasons, the Appropriate Legal Notices must display
 * the words "Powered by iteraplan".
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see http://www.gnu.org/licenses or write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301 USA.
 * 
 * You can contact iteratec GmbH headquarters at Inselkammerstr. 4
 * 82008 Munich - Unterhaching, Germany, or at email address info@iteratec.de.
 */
package de.iteratec.iteraplan.businesslogic.reports.query.options.GraphicalReporting.Line;

import de.iteratec.iteraplan.businesslogic.reports.query.options.GraphicalReporting.IGraphicalExportBaseOptions;

/**
 *
 */
public interface ILineOptionsBean extends IGraphicalExportBaseOptions {
  
  String getStartDateString();

  String getEndDateString();
  
  int getSelectedKeyAttributeTypeId(); 

}

WebContent/jsp/GraphicalReporting/Line/Manage.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@ taglib uri="http://tags.iteratec.de/iteratec-tags" prefix="itera"%>

<c:set var="resultPostSelection" value="true" scope="request" />
<c:set var="functionalPermission" value="${userContext.perms.userHasFuncPermGraphReporting}" scope="request" />
<c:set var="permissionCreateReports" value="${userContext.perms.userHasFuncPermGraphReportingCreate}" scope="request" />
<c:set var="permissionSaveReports" value="${userContext.perms.userHasFuncPermGraphReportingFull}" scope="request" />

<c:set var="dialogStep" value="${memBean.graphicalOptions.dialogStep}" />

<c:set var="chosenContentType">
  <fmt:message>
    <itera:write name="memBean" property="graphicalOptions.selectedBbType" escapeXml="false" />
  </fmt:message>
</c:set>

<c:set var="timeseriesAttributesActive" value="${memBean.graphicalOptions.timeseriesAttributesActive}"/>

<c:choose>
<c:when test="${functionalPermission == true}">
	<%-- adds the shortcut keys to quickly perform actions such as going back, 
	     sending a query or generating a graphical report --%>
	     
	<script type="text/javascript">
		addMiscShortcuts();
	</script>
 	
    <c:choose>
    <c:when test="${timeseriesAttributesActive == true}">
		<tiles:insertTemplate template="/jsp/GraphicalReporting/DiagramBreadcrumb.jsp" flush="true">
			<tiles:putListAttribute name="state_keys">
				<tiles:addAttribute value="graphicalExport.line.breadcrumbs.chooseElements" />
				<tiles:addAttribute value="graphicalExport.line.breadcrumbs.configuration" />
			</tiles:putListAttribute>
			<tiles:putListAttribute name="state_events">
				<tiles:addAttribute value="goToLineExportStep1" />
				<tiles:addAttribute value="goToLineExportStep2" />
			</tiles:putListAttribute>
			<tiles:putAttribute name="current_state_index" value="${dialogStep - 1}" />
		</tiles:insertTemplate>
	
		<h1><i class="${guiContext.activeDialogIconCssClass}"></i>&nbsp;<fmt:message key="graphicalExport.lineDiagram"/></h1>

		<c:choose>
		<c:when test="${dialogStep == 1}">
			<tiles:insertTemplate template="Step1.jsp" />
		</c:when>
		<c:when test="${(dialogStep == 2) && (permissionCreateReports == true)}">
    		<tiles:insertTemplate template="Step2.jsp" />
		</c:when>
		<c:otherwise>
  			<tiles:insertTemplate template="/jsp/common/AccessDenied.jsp" />
  		</c:otherwise>
		</c:choose>
	</c:when>
	<c:otherwise>
		<div class="alert alert-error">
			<h3><fmt:message key="graphicalExport.line.Error.Title" /></h3>
			<p><fmt:message key="graphicalExport.line.Error.Content" /></p>
		</div>
	</c:otherwise>
	</c:choose>	
</c:when>
<c:otherwise>
	<h1>false</h1>
  	<tiles:insertTemplate template="/jsp/common/AccessDenied.jsp" />
</c:otherwise>
</c:choose>

WebContent/jsp/GraphicalReporting/Line/Step1.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://tags.iteratec.de/iteratec-tags" prefix="itera"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>

<c:set var="chosenContentType">
  <fmt:message>
    <itera:write name="memBean" property="graphicalOptions.selectedBbType" escapeXml="false" />
  </fmt:message>
</c:set>



<tiles:insertTemplate template="/jsp/commonReporting/ShowSavedQuery.jsp">
	<tiles:putAttribute name="isGraphicalReporting" value="true" />
	<tiles:putAttribute name="selectedSavedQueryId" value="${memBean.graphicalOptions.savedQueryInfo.id}" />
	<tiles:putAttribute name="permissionCreateReports" value="${permissionCreateReports}" />
	<tiles:putAttribute name="permissionSaveReports" value="${permissionSaveReports}" />
	<tiles:putAttribute name="showBuildingBlockType" value="true" />
</tiles:insertTemplate>

<c:if test="${permissionCreateReports == 'true'}" >
	<p class="aligned"><fmt:message key="graphicalExport.line.helpContentType"/></p>

	<form:select path="graphicalOptions.selectedBbType" onchange="flowAction('selectLineType');">
	
	  <itera:define id="availableTypes_array" name="memBean" property="graphicalOptions.availableBbTypes" />
	  <c:forEach items="${availableTypes_array}" var="available" varStatus="countStatus">
	    <form:option value="${available}">
	      <fmt:message key="${available}" />
	    </form:option>
	  </c:forEach>
	</form:select>
	
	<hr />
	
	<p class="aligned">
		<fmt:message key="graphicalExport.line.helpStep1">
			<fmt:param>${chosenContentType}</fmt:param>
		</fmt:message>
	</p>
	
	<tiles:insertTemplate template="/jsp/GraphicalReporting/GraphicalReportingQueryForm.jsp" flush="true">
		<tiles:putAttribute name="hasPermission" value="${not empty availableTypes_array}"/>
		<tiles:putAttribute name="flowAction" value="goToLineExportStep2"/>
	</tiles:insertTemplate>
</c:if>